import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
  title: 'Japanese Lessons',
  tagline: 'Learn Japanese with structured lessons and vocabulary',
  favicon: 'img/favicon.ico',

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },
  url: 'https://sylhare.github.io',
  baseUrl: '/japanese/',

  organizationName: 'sylhare',
  projectName: 'japanese',

  onBrokenLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          // Exclude index files from autogenerated sidebar items (but keep them processable for category links)
          sidebarItemsGenerator: async ({
            defaultSidebarItemsGenerator,
            ...args
          }) => {
            const sidebarItems = await defaultSidebarItemsGenerator(args);
            const filterIndexFiles = (items: any[]): any[] => {
              return items
                .filter((item) => {
                  if (typeof item === 'string') {
                    return !item.endsWith('/index');
                  }
                  if (item.type === 'doc' && typeof item.id === 'string') {
                    return !item.id.endsWith('/index');
                  }
                  return true;
                })
                .map((item) => {
                  if (item.items && Array.isArray(item.items)) {
                    return {
                      ...item,
                      items: filterIndexFiles(item.items),
                    };
                  }
                  return item;
                });
          };
          return filterIndexFiles(sidebarItems);
          },
          editUrl:
            'https://github.com/sylhare/japanese/tree/main/',
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },
          editUrl:
            'https://github.com/sylhare/japanese/tree/main/',
          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    function webpackPlugin() {
      return {
        name: 'yaml-loader',
        configureWebpack(config) {
          config.module.rules.push({
            test: /\.ya?ml$/,
            use: 'yaml-loader',
          });
        },
      };
    },
  ],

  themeConfig: {
    // Replace with your project's social card
    image: 'img/docusaurus-social-card.jpg',
    googleGtag: {
      trackingID: 'G-YPX3TXS4S4',
    },
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Japanese Lessons',
      logo: {
        alt: 'Japanese Lessons Logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'lessonsSidebar',
          position: 'left',
          label: 'Lessons',
        },
        {
          type: 'doc',
          docId: 'reference/index',
          position: 'left',
          label: 'Kana',
        },
        {to: '/vocabulary', label: 'Vocabulary', position: 'left'},
        {
          href: 'https://github.com/sylhare/japanese',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Lessons',
          items: [
            {
              label: 'Getting Started',
              to: '/docs/lessons/intro',
            },
            {
              label: 'Grammar',
              to: '/docs/lessons/grammar/conjugation',
            },
            {
              label: 'Vocabulary',
              to: '/vocabulary',
            },
          ],
        },
        {
          title: 'Resources',
          items: [
            {
              label: 'Vocabulary System',
              to: '/vocabulary',
            },
            {
              label: 'Hiragana Chart',
              to: '/docs/reference/hiragana-chart',
            },
            {
              label: 'Katakana Chart',
              to: '/docs/reference/katakana-chart',
            },
          ],
        },
        {
          title: 'Development',
          items: [
            {
              label: 'GitHub Repository',
              href: 'https://github.com/sylhare/japanese',
            },
            {
              label: 'Development Docs',
              href: 'https://github.com/sylhare/japanese/tree/main/.github/docs',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Japanese Lessons. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
