import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Unified sidebar - shows all docs regardless of which navbar item is clicked
  lessonsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'lessons/intro',
      ],
    },
    {
      type: 'category',
      label: 'Grammar',
      link: {type: 'doc', id: 'lessons/grammar/index'},
      items: [{type: 'autogenerated', dirName: 'lessons/grammar'}],
    },
    {
      type: 'category',
      label: 'Conjugation',
      link: {type: 'doc', id: 'lessons/conjugation/index'},
      items: [{type: 'autogenerated', dirName: 'lessons/conjugation'}],
    },
    {
      type: 'category',
      label: 'Vocabulary',
      link: {type: 'doc', id: 'lessons/vocabulary/index'},
      items: [
        {type: 'autogenerated', dirName: 'lessons/vocabulary'},
        {
          type: 'category',
          label: '🔢 Numbers',
          link: {type: 'doc', id: 'lessons/numbers/index'},
          items: [{type: 'autogenerated', dirName: 'lessons/numbers'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'doc', id: 'reference/index'},
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],

  // Reference sidebar - use same content as lessons sidebar so all docs are visible
  referenceSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'lessons/intro',
      ],
    },
    {
      type: 'category',
      label: 'Grammar',
      link: {type: 'doc', id: 'lessons/grammar/index'},
      items: [{type: 'autogenerated', dirName: 'lessons/grammar'}],
    },
    {
      type: 'category',
      label: 'Conjugation',
      link: {type: 'doc', id: 'lessons/conjugation/index'},
      items: [{type: 'autogenerated', dirName: 'lessons/conjugation'}],
    },
    {
      type: 'category',
      label: 'Vocabulary',
      link: {type: 'doc', id: 'lessons/vocabulary/index'},
      items: [
        {type: 'autogenerated', dirName: 'lessons/vocabulary'},
        {
          type: 'category',
          label: '🔢 Numbers',
          link: {type: 'doc', id: 'lessons/numbers/index'},
          items: [{type: 'autogenerated', dirName: 'lessons/numbers'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'doc', id: 'reference/index'},
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
