import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * @fileoverview Sidebar configuration for Docusaurus documentation.
 * This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
 *
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 * Create as many sidebars as you want.
 */

/**
 * Shared sidebar configuration used by both lessons and reference sections.
 * Contains all documentation categories including Getting Started, Grammar,
 * Conjugation, Vocabulary, Numbers, and Reference materials.
 */
const sharedSidebarItems: SidebarsConfig[string] = [
  'intro',
  {
    type: 'category',
    label: 'Getting Started',
    items: [
      'lessons/intro',
    ],
  },
  {
    type: 'category',
    label: 'Grammar',
    link: {type: 'doc', id: 'lessons/grammar/index'},
    items: [{type: 'autogenerated', dirName: 'lessons/grammar'}],
  },
  {
    type: 'category',
    label: 'Conjugation',
    link: {type: 'doc', id: 'lessons/conjugation/index'},
    items: [{type: 'autogenerated', dirName: 'lessons/conjugation'}],
  },
  {
    type: 'category',
    label: 'Vocabulary',
    link: {type: 'doc', id: 'lessons/vocabulary/index'},
    items: [{type: 'autogenerated', dirName: 'lessons/vocabulary'}],
  },
  {
    type: 'category',
    label: 'Reference',
    link: {type: 'doc', id: 'reference/index'},
    items: [{type: 'autogenerated', dirName: 'reference'}],
  },
];

/**
 * Sidebar configuration object.
 * Both lessonsSidebar and referenceSidebar use the same shared configuration
 * to ensure consistent navigation across all documentation sections.
 */
const sidebars: SidebarsConfig = {
  lessonsSidebar: sharedSidebarItems,
  referenceSidebar: sharedSidebarItems,
};

export default sidebars;
